# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_auto_20160722_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllableattempt',
            name='expected_tone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syllableattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
