# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0005_subscriptionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionHistory',
        ),
    ]
