# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermgmt', '0007_auto_20160916_2351'),
        ('webui', '0006_auto_20160909_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageCampaignDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_family', models.CharField(max_length=100)),
                ('browser_version_string', models.CharField(max_length=100)),
                ('media_recorder_supported', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermgmt.AdCampaign')),
            ],
        ),
    ]
